language: node_js
node_js:
 - 'node'
 - 8
# before_script:
# - npm install
script:
- npm run lint
# - npm run test
deploy:
- provider: heroku
  api_key:
    secure: jt0OXzBasMH2UR5UinRZqvHAMfoE5DHztd1Pki6JFBCZmZoGdkOvB8/k24ZouZmRxG64lGfi8mTDIqXqver2csSl8D+l1b99PfgQBRSQi5HbcXsdL0fAccbl9r88l/EEeJieptFlMSTe6gfbQtVFZacEKbdNhpGfR8y2Rdh+vJbjRwyh1qG5QdJ1qzPHIBROoSEthNgHne2/143bOPgf9puK4Ztqba+YvWX5RaAdVsUKHIJEkn5f+Y+2B17Z34LNwlBvhbG5MBgZ6BUEerHcv5GiZR76m3T1rlml3OaqUiOFh4iuMbyx1yd2qnksNgW/4ZL4sKHMEtUx1h1jlWZSCz4i+WRqXZfkQfdytZTbsD1JKWF/Hi2AXgkR1F91mhgKbrSTykA+oq0xhhveibWxd9o4c0uWg5airMKOlTsYtFXP9lkpSJsfet7m5Zz1zPjoIxRDIHYZ+lo9nidojCPUQn9oQjQvp+Ib6J8KbA1IVL2AVM81JzsKB5p/ipdzcPWxUKSASR4Q2XkfKLtmJ9G5ioLm4YtcqfOX6O/CGuvoQtm1qQMAcIoGqOWyhYOJH79se0MATV3HCrJvYanYcfXLbGKfRnBFkJ4yjJ2+9RHlgJXJ4kSlDhS0DPVJp2JDL8NbvHF//VG3ah6jS22Wpk2lOIp/XmHjygFeZZT8voP8Z6c=
  app: 'shri-dz4-prod'
  on:
    repo: mrpq/shri_dz4
    all_branches: true
    tags: true
- provider: heroku
  api_key:
    secure: jt0OXzBasMH2UR5UinRZqvHAMfoE5DHztd1Pki6JFBCZmZoGdkOvB8/k24ZouZmRxG64lGfi8mTDIqXqver2csSl8D+l1b99PfgQBRSQi5HbcXsdL0fAccbl9r88l/EEeJieptFlMSTe6gfbQtVFZacEKbdNhpGfR8y2Rdh+vJbjRwyh1qG5QdJ1qzPHIBROoSEthNgHne2/143bOPgf9puK4Ztqba+YvWX5RaAdVsUKHIJEkn5f+Y+2B17Z34LNwlBvhbG5MBgZ6BUEerHcv5GiZR76m3T1rlml3OaqUiOFh4iuMbyx1yd2qnksNgW/4ZL4sKHMEtUx1h1jlWZSCz4i+WRqXZfkQfdytZTbsD1JKWF/Hi2AXgkR1F91mhgKbrSTykA+oq0xhhveibWxd9o4c0uWg5airMKOlTsYtFXP9lkpSJsfet7m5Zz1zPjoIxRDIHYZ+lo9nidojCPUQn9oQjQvp+Ib6J8KbA1IVL2AVM81JzsKB5p/ipdzcPWxUKSASR4Q2XkfKLtmJ9G5ioLm4YtcqfOX6O/CGuvoQtm1qQMAcIoGqOWyhYOJH79se0MATV3HCrJvYanYcfXLbGKfRnBFkJ4yjJ2+9RHlgJXJ4kSlDhS0DPVJp2JDL8NbvHF//VG3ah6jS22Wpk2lOIp/XmHjygFeZZT8voP8Z6c=
  app: 'shri-dz4-staging'
  on:
    repo: mrpq/shri_dz4
    branch: master
    tags: false

